### ISSUE TITLE
CAN pin schematic of B-G431B-ESC1

### ISSUE THREAD

**Issue by samkoesnadi** [Igitigit2/SimpleCanLib#1]
B-G431B-ESC1 is used here, and I can not find the pin schematic of the J1 CAN bus there. Would you be kind enough to provide the schematic here? I thank you in advance :))

**Comment by Igitigit2** [comment]
If the board is in front of you, motor phases facing left, daughter board on top, as in the picture below, the the pin sequence from left to right is:

Gnd, CAn L, CAN H, 5V

![image](https://github.com/Igitigit2/SimpleCanLib/assets/25508173/8d10896c-f4ea-46aa-b016-313f3d6c3a7e)

**Comment by samkoesnadi** [comment]
> If the board is in front of you, motor phases facing left, daughter board on top, as in the picture below, the the pin sequence from left to right is:
> 
> Gnd, CAn L, CAN H, 5V
> 
> ![image](https://user-images.githubusercontent.com/25508173/259452962-8d10896c-f4ea-46aa-b016-313f3d6c3a7e.png)

Thanks, I will try it out when I have the time 😊
